default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: visited_apps_development
test:
  <<: *default
  database: visited_apps_test
production:
  <<: *default
  database: visited_apps_production
